
package ProyectoFinal;
import javax.swing.table.DefaultTableModel;

public class VentanaHerramientas extends javax.swing.JFrame {
    ArregloProductos inventario = new ArregloProductos();
    DefaultTableModel modelo;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaHerramientas.class.getName());

    /**
     * Creates new form VentanaHerramientas
     */
    public VentanaHerramientas() {
        initComponents();
        String[] columnas = {"ID", "Nombre", "Marca", "Precio", "Stock"};
        modelo = new DefaultTableModel(null, columnas);
        jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCargarDatos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnCargarDatos.setText("Cargar Datos");
        btnCargarDatos.addActionListener(this::btnCargarDatosActionPerformed);

        jLabel1.setText("Nombre");

        jLabel2.setText("Marca");

        jLabel3.setText("Precio");

        jLabel4.setText("Stock");

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        txtMarca.addActionListener(this::txtMarcaActionPerformed);

        txtPrecio.addActionListener(this::txtPrecioActionPerformed);

        txtStock.addActionListener(this::txtStockActionPerformed);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnRegistrar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCargarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnRegistrar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnCargarDatos)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDatosActionPerformed
       if (inventario.tamaño() == 0){
           inventario.agregar(new Producto(1, "Martillo", "Stanley", 25.50, 10));
           inventario.agregar(new Producto(2, "Alicate", "Tramotnina", 15.00, 5));
           inventario.agregar(new Producto(3, "Destornillador", "Truper", 8.20, 20));
       }
       mostrarProductos();
    }//GEN-LAST:event_btnCargarDatosActionPerformed
    
    private void mostrarProductos(){
        modelo.setRowCount(0);
        
        for (int i = 0; i < inventario.tamaño(); i++) {
            Producto p = inventario.obtener(i);
            
            Object[] fila = {
                p.getId(),
                p.getNombre(),
                p.getMarca(),
                p.getPrecio(),
                p.getStock(),
            };
            
            modelo.addRow(fila);
        }
    }   
    
   private void limpiarCampos(){
       txtNombre.setText("");
       txtMarca.setText("");
       txtPrecio.setText("");
       txtStock.setText("");
       txtNombre.requestFocus();
   }
    
    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
    try{
    String nombre = txtNombre.getText().trim();
    String marca = txtMarca.getText().trim();
    
    if (nombre.isEmpty() || marca.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Completa el nombre y la marca del producto.");
        return;
    }
    
    if (txtPrecio.getText().trim().isEmpty() || txtStock.getText().trim().isEmpty()){
        javax.swing.JOptionPane.showMessageDialog(this,
                "Completa el precio y el sstock del producto.");
        return;
    }
    
    double precio = Double.parseDouble(txtPrecio.getText().trim());
    int stock = Integer.parseInt(txtStock.getText().trim());
    
    if (precio <= 0){
        javax.swing.JOptionPane.showMessageDialog(this,
                "El precio debe ser mayot a 0.");
        return;
    }
    
    if (stock < 0){
        javax.swing.JOptionPane.showMessageDialog(this,
                "El stock no puede ser negativo");
        
        return;
    }
    
    int nuevoId = inventario.generarNuevoId();
    
    Producto nuevo = new Producto(nuevoId, nombre, marca, precio, stock);
    inventario.agregar(nuevo);
    mostrarProductos();
    limpiarCampos();
    
    javax.swing.JOptionPane.showMessageDialog(this, 
                 "¡Producto registrado con exito!");
    
    }//GEN-LAST:event_btnRegistrarActionPerformed
    catch (NumberFormatException e){
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Error: ingresa números validos en Precio y Stock.", 
                "Error de formato", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       String dato = javax.swing.JOptionPane.showInputDialog(this,
               "Ingrese el ID del producto a buscar:");
       
       if (dato == null) {
           return;
       }
       
       if (dato.trim().isEmpty()) {
           javax.swing.JOptionPane.showMessageDialog(this,
                   "Debe ingresar un ID");
           return;
       }
       
       try {
           int idBusqueda = Integer.parseInt(dato.trim());
           
           Producto p = inventario.buscarPorId(idBusqueda);
           
           if (p != null) {
               modelo.setRowCount(0);
               
               Object[] fila = {
                   p.getId(),
                   p.getNombre(),
                   p.getMarca(),
                   p.getPrecio(),
                   p.getStock(),
               };
               
               modelo.addRow(fila);
               
               txtNombre.setText(p.getNombre());
               txtMarca.setText(p.getMarca());
               txtPrecio.setText(String.valueOf(p.getPrecio()));
               txtStock.setText(String.valueOf(p.getStock()));
               
               javax.swing.JOptionPane.showMessageDialog(this,
                       "Producto encontrado.");
           }else{
               javax.swing.JOptionPane.showMessageDialog(this,
                       "No existe un producto con ese ID.");
           }
           
    }//GEN-LAST:event_btnBuscarActionPerformed
        catch (NumberFormatException e){
        javax.swing.JOptionPane.showMessageDialog(this, 
                "EL Id debe ser un número entero", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
    } 
       } 
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       String dato = javax.swing.JOptionPane.showInputDialog(this,
               "Ingrese el ID del proudcto:");
       
       if (dato == null) {
           return;
    }//GEN-LAST:event_btnEliminarActionPerformed
if (dato.trim().isEmpty()){
        javax.swing.JOptionPane.showMessageDialog(this,
                "Debe ingresar un ID:");
        return;
    }
    
    try{
        int idEliminar = Integer.parseInt(dato.trim());
        
        Producto p = inventario.buscarPorId(idEliminar);
        
        if (p == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No existe un producto con ese ID.");
            return;
        }
        
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Está seguro que desea eliminar el producto?\n\n"
                + "ID: " + p.getId() + "\n"
                + "Nombre: " + p.getNombre() + "\n"
                + "Marca: " + p.getMarca(),
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION){
            boolean eliminado = inventario.eliminarPodId(idEliminar);
            if (eliminado) {
                mostrarProductos();
                limpiarCampos();
                
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Producto eliminado correctamente");
            }
        }
                
    }
       catch (NumberFormatException e){
        javax.swing.JOptionPane.showMessageDialog(this, 
                "EL Id debe ser un número entero", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    } 
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String dato = javax.swing.JOptionPane.showInputDialog(this,
                "Ingrese el ID del producto a actualizar.");
        
        if (dato == null) {
            return;
        }
        
        if (dato.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe ingresar un ID.");
            return;
        }
        try {
            int idActualizar = Integer.parseInt(dato.trim());
            
            Producto p = inventario.buscarPorId(idActualizar);
            
            if (p == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No existe un producto con ese ID.");
                return;
            }
            
            String nombre = txtNombre.getText().trim();
            String marca = txtMarca.getText().trim();
            
            if (nombre.isEmpty() || marca.isEmpty()){
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Completa el nombre y la marca del producto");
                return;
            }
            
            double precio = Double.parseDouble(txtPrecio.getText().trim());
            int stock = Integer.parseInt(txtStock.getText().trim());
            
            if (precio <=0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "El precio debe ser mayor a 0.");
                return;
            }
            
            if (stock < 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "El stock no puede ser negativo.");
                return;
            }
            
            boolean actualizado = inventario.actualizarProducto(idActualizar, nombre, marca, precio, stock);
            
            if (actualizado) {
                mostrarProductos();
                limpiarCampos();
                
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Producto actualizado correctamente.");
            }
        }
        catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "El ID, precio y stock deben ser valores numéricos válidos.",
                "Eror",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_btnActualizarActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> new VentanaHerramientas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCargarDatos;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
